from .schemas import (
    AnalysisCapability,
    BusinessPurpose,
    CapabilityStage,
    ExecutionConstraints,
    MaturityLevel,
    SemanticPrimitive,
)


def default_analysis_capabilities() -> list[AnalysisCapability]:
    """
    Built-in metadata catalog mapped to existing analysis plugins.
    """

    return [
        AnalysisCapability(
            capability_id="cap_descriptive_statistics",
            display_name="Descriptive Statistics",
            description="Summarize central tendency and spread for numeric columns.",
            investigation_stage=CapabilityStage.OBSERVE,
            business_purpose=BusinessPurpose.DESCRIBE,
            required_input_types=["dataset_profile", "tabular_dataset"],
            supported_semantic_primitives=[SemanticPrimitive.NUMERIC],
            expected_outputs=["column_statistics", "distribution_summary"],
            execution_constraints=ExecutionConstraints(minimum_rows=1, minimum_columns=1),
            dependencies=["cap_frequency_distribution"],
            tags=["baseline", "summary", "statistics"],
            maturity_level=MaturityLevel.STABLE,
            version="1.0.0",
            plugin_key="Descriptive Statistics",
        ),
        AnalysisCapability(
            capability_id="cap_frequency_distribution",
            display_name="Frequency Distribution",
            description="Measure value frequencies for categorical and boolean attributes.",
            investigation_stage=CapabilityStage.OBSERVE,
            business_purpose=BusinessPurpose.DESCRIBE,
            required_input_types=["dataset_profile", "tabular_dataset"],
            supported_semantic_primitives=[SemanticPrimitive.CATEGORICAL, SemanticPrimitive.BOOLEAN],
            expected_outputs=["frequency_table", "proportion_summary"],
            execution_constraints=ExecutionConstraints(minimum_rows=1),
            dependencies=[],
            tags=["distribution", "categorical"],
            maturity_level=MaturityLevel.STABLE,
            version="1.0.0",
            plugin_key="Frequency Distribution",
        ),
        AnalysisCapability(
            capability_id="cap_correlation_analysis",
            display_name="Correlation Analysis",
            description="Assess linear relationships across numeric variables.",
            investigation_stage=CapabilityStage.EXPLAIN,
            business_purpose=BusinessPurpose.DIAGNOSE,
            required_input_types=["dataset_profile", "tabular_dataset"],
            supported_semantic_primitives=[SemanticPrimitive.NUMERIC],
            expected_outputs=["pairwise_coefficients", "relationship_strength"],
            execution_constraints=ExecutionConstraints(minimum_rows=3, minimum_columns=2),
            dependencies=["cap_descriptive_statistics"],
            tags=["relationships", "numeric", "explanatory"],
            maturity_level=MaturityLevel.STABLE,
            version="1.0.0",
            plugin_key="Correlation Analysis",
        ),
        AnalysisCapability(
            capability_id="cap_regression_analysis",
            display_name="Regression Analysis",
            description="Estimate directional associations between predictors and outcomes.",
            investigation_stage=CapabilityStage.EXPLAIN,
            business_purpose=BusinessPurpose.DIAGNOSE,
            required_input_types=["dataset_profile", "tabular_dataset", "mapped_target"],
            supported_semantic_primitives=[SemanticPrimitive.NUMERIC],
            expected_outputs=["model_coefficients", "fit_metrics"],
            execution_constraints=ExecutionConstraints(minimum_rows=10, minimum_columns=2),
            dependencies=["cap_correlation_analysis"],
            tags=["modeling", "explanation"],
            maturity_level=MaturityLevel.BETA,
            version="1.0.0",
            plugin_key="Regression Analysis",
        ),
        AnalysisCapability(
            capability_id="cap_outlier_detection",
            display_name="Outlier Detection",
            description="Identify extreme observations in numeric distributions.",
            investigation_stage=CapabilityStage.VALIDATE,
            business_purpose=BusinessPurpose.DETECT_ANOMALY,
            required_input_types=["dataset_profile", "tabular_dataset"],
            supported_semantic_primitives=[SemanticPrimitive.NUMERIC],
            expected_outputs=["outlier_indices", "outlier_ratios"],
            execution_constraints=ExecutionConstraints(minimum_rows=5, minimum_columns=1),
            dependencies=["cap_descriptive_statistics"],
            tags=["quality", "anomaly"],
            maturity_level=MaturityLevel.STABLE,
            version="1.0.0",
            plugin_key="Outlier Detection",
        ),
        AnalysisCapability(
            capability_id="cap_ttest_analysis",
            display_name="T-Test Analysis",
            description="Compare mean differences between two groups.",
            investigation_stage=CapabilityStage.VALIDATE,
            business_purpose=BusinessPurpose.COMPARE,
            required_input_types=["dataset_profile", "tabular_dataset", "group_mapping"],
            supported_semantic_primitives=[SemanticPrimitive.NUMERIC, SemanticPrimitive.CATEGORICAL],
            expected_outputs=["test_statistic", "p_value", "group_difference"],
            execution_constraints=ExecutionConstraints(minimum_rows=8, minimum_columns=2),
            dependencies=[],
            tags=["hypothesis-testing", "comparison"],
            maturity_level=MaturityLevel.BETA,
            version="1.0.0",
            plugin_key="T-Test Analysis",
        ),
        AnalysisCapability(
            capability_id="cap_chi_square_analysis",
            display_name="Chi-Square Analysis",
            description="Evaluate association across categorical variables.",
            investigation_stage=CapabilityStage.VALIDATE,
            business_purpose=BusinessPurpose.VALIDATE_ASSUMPTION,
            required_input_types=["dataset_profile", "tabular_dataset"],
            supported_semantic_primitives=[SemanticPrimitive.CATEGORICAL, SemanticPrimitive.BOOLEAN],
            expected_outputs=["chi_square_statistic", "p_value", "association_strength"],
            execution_constraints=ExecutionConstraints(minimum_rows=10, minimum_columns=2),
            dependencies=["cap_frequency_distribution"],
            tags=["hypothesis-testing", "categorical"],
            maturity_level=MaturityLevel.BETA,
            version="1.0.0",
            plugin_key="Chi-Square Analysis",
        ),
        AnalysisCapability(
            capability_id="cap_random_forest",
            display_name="Random Forest",
            description="Ensemble capability for robust predictive modeling.",
            investigation_stage=CapabilityStage.RECOMMEND,
            business_purpose=BusinessPurpose.CLASSIFY,
            required_input_types=["dataset_profile", "tabular_dataset", "mapped_target"],
            supported_semantic_primitives=[SemanticPrimitive.NUMERIC, SemanticPrimitive.CATEGORICAL],
            expected_outputs=["feature_importance", "prediction_scores"],
            execution_constraints=ExecutionConstraints(minimum_rows=30, minimum_columns=2),
            dependencies=["cap_descriptive_statistics"],
            tags=["ensemble", "predictive"],
            maturity_level=MaturityLevel.BETA,
            version="1.0.0",
            plugin_key="Random Forest",
        ),
    ]